name: Lint LCAF Terraform Module
description: Lints a Terraform Module using LCAF
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Setup Repo
      shell: bash
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod +x ~/repo
        export PATH=$PATH:~

    - name: Install ASDF
      uses: asdf-vm/actions/setup@v3

    - name: Configure LCAF
      shell: bash
      run: |
        git config --add user.name github_actions
        git config --add user.email actions_noreply@github.com
        make configure

    - name: Lint Repository
      shell: bash
      run: |
        make lint
